# Project information

site_name: 'ZOZOZOZO ZOZOZOZO'
site_description: 'In this course we will learn how to deploy websites in continuous deployment with static site generators. We will try to understand numerous Web Dev and hosting concepts and to practice them.'
site_author: 'François-Emmanuel Goffinet'
site_url: 'https://demo-mkdocs-material.netlify.com/'
google_analytics:
  - 'UA-21733018-12'
  - 'auto'
copyright: 'Copyright &copy; 2018 François-Emmanuel Goffinet'
repo_name: 'goffinet/demo-mkdocs-material'
repo_url: 'https://github.com/goffinet/demo-mkdocs-material/'

# Theme

theme:
  name: null
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true


# Options

  language: fr
  feature:
    tabs: false
  palette:
    primary: 'blue'
    accent: 'purple'
  font:
    text: Roboto
    code: Roboto Mono
  logo:
    icon: 'school'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/goffinet'
    - type: 'twitter'
      link: 'https://twitter.com/fegoffinet'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/fegoffinet/'
    - type: 'building-o'
      link : 'https://www.goffinet.org'
    - type: 'book'
      link : 'https://biblio.goffinet.org'

# Extensions

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Content structure

pages:
- 'Présentation de la formation': 'index.md'
- '1. Premier projet en déploiement continu':
  - "Premier projet de déploiement continu": '01-00-premier-projet-en-deploiement-continu.md'
  - "1. Le déploiement continu": '01-01-deploiement-continu.md'
  - "2. Générateur de site statique": '01-02-generateur-de-site-statique.md'
  - "3. Gestionnaire de version Git et service GitHub": '01-03-gestionnaire-de-version-git-et-github.md'
  - "4. Planification du projet": '01-04-planification-du-projet.md'
  - "5. Service Netlify": '01-05-service-netlify.md'
  - "6. Configuration DNS": '01-06-configuration-dns.md'
  - "7. HTTPS gratuit à la demandes": '01-07-https-gratuit-a-la-demande.md'
  - "8. Personnalisation du projet": '01-08-personalisation-du-projet.md'
- '2. Autre projets avec générateur de site statique': 'autres-projets-avec-generateur-de-site-statique.md'
- '3. Apprendre à écrire en Markdown': 'noway.md'
